AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'dependabot/**/*'

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/OpenStructUse:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 6
Metrics/PerceivedComplexity:
  Max: 25
Naming/VariableNumber:
  Enabled: false
Layout/LineLength:
  Max: 200
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Bundler/OrderedGems:
  Enabled: false
Rails/EnvironmentVariableAccess:
  AllowReads: true
Rails/CreateTableWithTimestamps:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Rails/ApplicationController:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
Rails/NotNullColumn:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - staging
    - test
RSpec/AnyInstance:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
RSpec/ScatteredSetup:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/VariableName:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
RSpec/FactoryBot/CreateList:
  EnforcedStyle: n_times
RSpec/Be:
  Enabled: false
RSpec/VoidExpect:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 7
RSpec/ContextWording:
  Enabled: false
